[project]
name = "vecsim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.5.2",
    "numpy>=2.4.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
